[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-mocha.toml", "~/.config/alacritty/bindings.toml"]

[cursor]
thickness = 0.15

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

# the default family of the font is set in the normal section
[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[selection]
save_to_clipboard = false
semantic_escape_chars = ''',â”‚`|:"' ()[]{}<>	'''

[window]
dynamic_title = true
opacity = 0.97
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 19

[window.position]
x = 0
y = 0
