[workspace]
name = "dotfiles"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"
authors = ["Alexander Ivanov <alexander.valentinov.ivanov@gmail.com>"]

[tasks]

[dependencies]
python = ">=3.10"
setuptools_scm = "*"

[feature.lint.tasks]
pre-commit-install = "pixi run -e lint pre-commit install"
pre-commit-run = "pixi run -e lint pre-commit run -a"

[feature.lint.dependencies]
pre-commit = "*"

[environments]
lint = { features = ['lint'] }
